### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by Miaourt** [windicss/windicss-intellisense#1]
First ! Thanks for your work on this extension !

We are quite a few using [VSCodium](https://vscodium.com/), a release of VSCode which isn't proprietary and doesn't bundle Microsoft telemetry, and it doesn't use Microsoft's marketplace for their extensions.

They use [Open VSX](https://open-vsx.org/) , which is basically the same but they don't have obscure policies preventing custom clients to download their VSX packages.

Publishing on there is [quite easy](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) and I think it can be done when you have time, meanwhile for those like me using VSCodium we can download the extension manually from the marketplace website for now.

**Comment by voorjaar** [comment]
https://open-vsx.org/extension/voorjaar/windicss-intellisense done.
