### ISSUE TITLE
discussion: multiline class attribute (wrapping)

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#10]
I would like it more if the class attribute gets wrapped to multiple lines instead of folding with replace character. Maybe an option to choose? like below, or should this be something the code formatter handles? Mine does not, it does just breaks multiple attributes into multiple lines, but not the content of class attribute itself. We might have loops with formatters if we change this, since they will try to put it back onto one line

```svelte
<div 
  class="sm:hover:bg-amber-100
        bg-indigo-900 flex flex-col min-w-100vw
        min-h-100vh items-center justify-center
        ">
  <Widget />
</div>
```

**Comment by alexanderniebuhr** [comment]
cc @voorjaar what do you think, about this. I am still sure it might conflict with code formatters.

**Comment by voorjaar** [comment]
> cc @voorjaar what do you think, about this. I am still sure it might conflict with code formatters.

It is code formats...just change your formatter setup, and you can achieve this...

**Comment by alexanderniebuhr** [comment]
i'll try
