### ISSUE TITLE
Support for scss filetype

### ISSUE THREAD

**Issue by Mankot** [windicss/windicss-intellisense#103]
Per default .scss files are not supported.  I tried adding it through the includeLanguages configuration, but it only supports html/js patterns.  Adding the following to extension.js works for me so far:

```js
var fileTypes = [
...
    {
        extension: 'scss',
        patterns: stylesPatterns,
    },
];
```

Is there a reason why scss files are not included?
Thank you for the great work on windicss.
Cheers.

**Comment by alexanderniebuhr** [comment]
There is no particular reason. This extension ist still in beta phase, so it just was not requested before. We should update the option to allow also stylePattern.

**Comment by Mankot** [comment]
Awesome, thanks for adding this. Adding scss support through the settings works now:
```json
  "windicss.includeLanguages": {
    "scss": "css",
  },
```
Thank you!
