### ISSUE TITLE
[Question] How to enable suggestion in dynamic Vue class

### ISSUE THREAD

**Issue by harrytran998** [windicss/windicss-intellisense#107]
There is some way to write a dynamic class in Vue.
1. 
```vue
<hr :class="{['w-full']: orientation === 'horizontal'}" />
```
2. 
```vue
<hr :class="[{ 'w-full': orientation === 'horizontal'}]" />
```

But I don't see the suggestion anymore when using this! Hope you guy can improve that!

**Comment by alexanderniebuhr** [comment]
just going to close since there was no much activity lately, if some issue still exists please reopen a new issue

**Comment by joker77877** [comment]
Doesn't seem to solve this problem。
<img width="869" alt="image" src="https://user-images.githubusercontent.com/62642184/199447654-22d58b90-dd79-4b8e-b4b4-7d2e0e5c7483.png">
