### ISSUE TITLE
Why don't I install Auto prompt? Do you want to configure anything

### ISSUE THREAD

**Issue by weizheng1992** [windicss/windicss-intellisense#113]

**Comment by alexanderniebuhr** [comment]
what do you mean?

**Comment by weizheng1992** [comment]
https://user-images.githubusercontent.com/10727313/117395464-8af91900-af2a-11eb-9f50-f2089869751f.mov

![Uploading 屏幕快照 2021-05-07 上午11.51.52.png…]()

**Comment by alexanderniebuhr** [comment]
It actually should work. Which file format do you have? Do you use an `class` attribute or something else such as `:class` or `className`

**Comment by weizheng1992** [comment]
https://user-images.githubusercontent.com/10727313/117443421-b26fd600-af6a-11eb-85e2-48d1333f505d.mov

**Comment by weizheng1992** [comment]
> 
> ## System Info
> * `vite` version: 2.1.0
> * `react` version: 17.0.0
> * vite-plugin-windicss version: 0.11.1
> * Operating System: macOS 10.14.6
> * Node version: v12.20.2
> * Package manager (npm/yarn/pnpm) and version: yarn 1.22.10
>

**Comment by fliu2476** [comment]
same issue, it doesn't on VSCode 1.56.2.

**Comment by alexanderniebuhr** [comment]
Is this bug still happens with v0.16.1

**Comment by alexanderniebuhr** [comment]
I just reproduced it

/cc @voorjaar I think we need to add `className` to vue, react, and svelte pattern?!
https://github.com/windicss/windicss-intellisense/blob/7e8e9a6a5faad66982192206f2e2ac726bf26d19/src/utils/filetypes.ts#L21

**Comment by voorjaar** [comment]
from v0.16.3 we supported `className=` and `className = {`

If there are still missing patterns, they can be added through the following configuration.

```js
"windicss.includeLanguages": {
  "ruest": "html", // css, js
  "svelte": {
    "type": "css"
  },
  "javascriptreact": {
    "type": "js",
    "patterns": ["@apply\s+\S+$", "..." ],
  },
}
```

**Comment by fliu2476** [comment]
this extension conflicts with [vscode-auto-rename-tag](https://github.com/formulahendry/vscode-auto-rename-tag).
disable the auto-rename-tag and restart vscode, the windicss intellisense works fine.
