### ISSUE TITLE
add config option to choose style of color swatches

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#12]
add config option to activate optional coloring mode, instead of swatches
(inspiration https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize)

<img width="660" alt="Bildschirmfoto 2021-02-25 um 20 09 23" src="https://user-images.githubusercontent.com/45965090/109204283-71f31f80-77a5-11eb-99f8-da831ee95263.png">

**Comment by alexanderniebuhr** [comment]
cc @voorjaar do you like the idea, or should be abandon it?

**Comment by voorjaar** [comment]
Yes. Not bad. Can you show me the preview then? This may cause confusion with syntax highlighting. If it looks good, we can switch to this.

**Comment by alexanderniebuhr** [comment]
i would prefer both ways, opt in with setting

**Comment by alexanderniebuhr** [comment]
i am not sure about this anymore... seems distracting with inline classes. and for CSS style tags, we just use https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize

**Comment by voorjaar** [comment]
This feature will not be implemented, close it for now.
