### ISSUE TITLE
feat: intellisense for generated arbitrary values

### ISSUE THREAD

**Issue by eggsy** [windicss/windicss-intellisense#120]
This is (I believe) from Tailwind's updated intellisense. This might actually be helpful in some cases and I'd be glad to see this on Windi's extension too!

![image](https://user-images.githubusercontent.com/13917975/117988418-11a36100-b344-11eb-9b28-a1557e179fbd.png)

**Comment by voorjaar** [comment]
please upgrade to 0.16.1, which has been supported.
