### ISSUE TITLE
custom css themes not recognized by syntax check

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#124]
i believe this update is causing some false positives with extended theme colors.

> ![image](https://user-images.githubusercontent.com/17879327/118326335-24b15f00-b505-11eb-8007-0414c3876594.png)
> as you can see, the value itself is valid and resolves correctly.

this issue vanishes when reverting back to 0.13.1.

_Originally posted by @vaaski in https://github.com/windicss/windicss-intellisense/issues/121#issuecomment-841492666_

**Comment by alexanderniebuhr** [comment]
@vaaski thanks for your help. I will fix it today

**Comment by vaaski** [comment]
excellent, thank you very much.

**Comment by moisesbites** [comment]
Thank you for your help.
