### ISSUE TITLE
Multiline class breaks the intellisense 

### ISSUE THREAD

**Issue by pikax** [windicss/windicss-intellisense#126]
When the class names are not in the same line as `class` the autocomplete stops working.

```html
// WORKS
<div class="bg-transparent flex-nowrap">
  
// DOESNT WORK
<div class="bg-transparent 
            flex-nowrap">
```

[windicss-intellisense-bug.zip](https://github.com/windicss/windicss-intellisense/files/6483714/windicss-intellisense-bug.zip)  `index.html`

**Comment by alexanderniebuhr** [comment]
correct. We changed some time ago to use lineText of the current line of the cursors, to match with regex if it is in an attribute for completion. If on multiline, the second line has no idea that it is in an class attribute.

We did that technical change to improve performance & mitigate false positives if autocomplete is used in other places in code.

If you have any idea or an fix which still has performance and usage in mind, we are very welcome for any contribution.

**Comment by voorjaar** [comment]
What are you talking about ??!

> correct. We changed some time ago to use lineText of the current line of the cursors, to match with regex if it is in an attribute for completion. If on multiline, the second line has no idea that it is in an class attribute.
> 
> We did that technical change to improve performance & mitigate false positives if autocomplete is used in other places in code.
> 
> If you have any idea or an fix which still has performance and usage in mind, we are very welcome for any contribution.

**Comment by alexanderniebuhr** [comment]
@voorjaar I am talking about that completions are not shown always and anywhere, they are just shown in places where regex patterns for the filetype matches. On multiline non of the defined regex will match, therefor no completion item will be returned. 

https://github.com/windicss/windicss-intellisense/blob/d9b8cccfd719294aa64ddce9fb17429807b6495d/src/lib/completions.ts#L28-L33
https://github.com/windicss/windicss-intellisense/blob/d9b8cccfd719294aa64ddce9fb17429807b6495d/src/utils/filetypes.ts#L3-L7

**Comment by alexanderniebuhr** [comment]
We could to an multi line regex on whole content of current editor to see if there is a positive match for something like =" and "

**Comment by voorjaar** [comment]
> @voorjaar I am talking about that completions are not shown always and anywhere, they are just shown in places where regex patterns for the filetype matches. On multiline non of the defined regex will match, therefor no completion item will be returned.
> 
> https://github.com/windicss/windicss-intellisense/blob/d9b8cccfd719294aa64ddce9fb17429807b6495d/src/lib/completions.ts#L28-L33
> 
> 
> https://github.com/windicss/windicss-intellisense/blob/d9b8cccfd719294aa64ddce9fb17429807b6495d/src/utils/filetypes.ts#L3-L7
> 
> **UPDATE:** related PR [0c6853b#diff-78eac487e28e05b9faa1aec69c36469ea1ba245fe38c037aeef03ac18a60521a](https://github.com/windicss/windicss-intellisense/commit/0c6853bf2307791e6494c751cf7e7afde65ce62c#diff-78eac487e28e05b9faa1aec69c36469ea1ba245fe38c037aeef03ac18a60521a)
> **UPADTE:** was introduced to mitigate following issue #2

This is a very stupid change, cross line is a common situation, we will never ever to give up support it. Please don’t talk to me about what performance issues. Before considering performance, think about the user experience ok?

**Comment by voorjaar** [comment]
Don't upload this commit until you find a multi-line alternative.

> We could to an multi line regex on whole content of current editor
> to see if there is a positive match for something like `="` and `"`
> 
> This would tell if the cursor is in an attribute either single- or multiline or not..
> 
> I don't agree on it showing completions everywhere

Next time, please don't change the code without an alternative.

**Comment by alexanderniebuhr** [comment]
@voorjaar No the change is not stupid, it was one way to handle #2 & #17. There is place for improvement! Yes I know that user experience should be considered before performance.. 

please look  at #2 & #17 .I think the experience with the old version is not good either.

**Comment by alexanderniebuhr** [comment]
@voorjaar i have [suggested an idea](https://github.com/windicss/windicss-intellisense/pull/127) for an fix.. check it, test it! If you don't like the idea - don't merge it.
It should fix multiline attributes (all attributes) and `<style>`  tags ...

**Comment by harrytran998** [comment]
Firstly, I hope your team can be calm down, both! teamwork what matters 😁.
I use Windi because your team!

Btw, I had a problem which likes the issue's title. Hope you guy can fix it soon 😊.

**Comment by voorjaar** [comment]
> Firstly, I hope your team can be calm down, both! teamwork what matters 😁.
> I use Windi because your team!
> 
> Btw, I had a problem which likes the issue's title. Hope you guy can fix it soon 😊.

Thank you. However I must point out that this is a very serious mistake and Alex’s first reply made me think he was making excuses, then I apologized for my harsh tone @alexanderniebuhr .
