### ISSUE TITLE
feat req: add rem to px preview

### ISSUE THREAD

**Issue by reslear** [windicss/windicss-intellisense#13]
you are so cool, thankyou big bro @voorjaar for this extension, it's best start year work)

but, i caught little flashback )
 
https://github.com/tailwindlabs/tailwindcss-intellisense/issues/200

**Comment by voorjaar** [comment]
Is rem*16 hard to calculate 😂?

**Comment by alexanderniebuhr** [comment]
@reslear thank you for the idea!! if you feel it, you can try to submit a pr and we go from their. Otherwise this issue is tagged with good first issue, so people you would be willed to help can take this. Please understand core contributors are working on bugs first :)

**Comment by reslear** [comment]
@voorjaar but i'm about tw number,  4tw-16px-1rem (for example 300px in tw ?) need use https://tailwindcss-calculator.com/

**Comment by voorjaar** [comment]
![Screen Shot 2021-03-02 at 15 15 11](https://user-images.githubusercontent.com/69119532/109612317-8307ac00-7b6a-11eb-9589-07d49676a482.png)
