### ISSUE TITLE
Can compile a new withe the VS Code version of `1.48.2`?

### ISSUE THREAD

**Issue by qiutian00** [windicss/windicss-intellisense#134]
![image](https://user-images.githubusercontent.com/24382500/118788591-83405980-b8c6-11eb-8fc1-e2dcf4d89771.png)

**Comment by alexanderniebuhr** [comment]
/cc @voorjaar the requested VS Code version is an very old version. Current is 1.56

How to handle?

**Comment by voorjaar** [comment]
I think we can use an older version, it's not a problem. I will do some research and find the most suitable version to fix that `engine` version.

**Comment by voorjaar** [comment]
let's use `engine: ^1.42.1`

**Comment by qiutian00** [comment]
Where?  Can we download this `^1.42.1` version of VS Code.

**Comment by voorjaar** [comment]
> Where? Can we download this `^1.42.1` version of VS Code.

I mean change this https://github.com/windicss/windicss-intellisense/blob/main/package.json#L9

**Comment by qiutian00** [comment]
I misunderstood

> > Where? Can we download this `^1.42.1` version of VS Code.
> 
> I mean change this https://github.com/windicss/windicss-intellisense/blob/main/package.json#L9

misunderstood.

**Comment by qiutian00** [comment]
> > Where? Can we download this `^1.42.1` version of VS Code.
> 
> I mean change this https://github.com/windicss/windicss-intellisense/blob/main/package.json#L9

misunderstood

**Comment by voorjaar** [comment]
The test is complete, 1.42.1 does not work, and 1.47.3 works normally.

**Comment by qiutian00** [comment]
Ooh, I download this version to use the windicss,  thanks.

**Comment by voorjaar** [comment]
Anyway, it's a problem, should been fixed.
