### ISSUE TITLE
suggestion: add a extension settings such as headwind.classRegex

### ISSUE THREAD

**Issue by LanJamRom** [windicss/windicss-intellisense#135]
it's not a correct prompt when i code in vue3
![image](https://user-images.githubusercontent.com/41603622/118790921-c996b800-b8c8-11eb-90dc-4a2bdef7b825.png)
Windicss IntelliSecse can work as correct IntelliSense what I expected
![image](https://user-images.githubusercontent.com/41603622/118792350-29da2980-b8ca-11eb-9689-a757c6175403.png)

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss-intellisense/commit/db0d32ef3bda5a13de0d89298c882458ef2aef48 already add that. not release yet.

**Comment by voorjaar** [comment]
please upgrade to 0.16.1, which has been fixed.
