### ISSUE TITLE
Completion items makes it hard to select variables properties

### ISSUE THREAD

**Issue by V-ed** [windicss/windicss-intellisense#136]
![image](https://user-images.githubusercontent.com/16652915/118831169-89661400-b88d-11eb-95a1-f9436bc828cb.png)
---
![image](https://user-images.githubusercontent.com/16652915/118831205-9420a900-b88d-11eb-9dad-001489f46e6e.png)

---

I also use intellisense to help me find the different properties of objects, which this kind of prevents unless I turn off the `Windicss : Enable Code Completion` vscode setting.

I could simply find my properties in Svelte's script tag (even though this isn't possible in 100% of the cases), but Windicss's completion items also appears in the `<script>` tags, as shown below (with an even worse example) :

![image](https://user-images.githubusercontent.com/16652915/118831859-1c06b300-b88e-11eb-9817-36c510924aa9.png)
---
![image](https://user-images.githubusercontent.com/16652915/118831905-22952a80-b88e-11eb-9d04-d34290b4d5e3.png)

---

However, I do like completions and would prefer to keep them - anything I can change to vscode's settings to put variables properties above Windicss's completion or is this something that only this extension can manage?

**Comment by alexanderniebuhr** [comment]
you can try to disable `windicss.enableEmmetCompletion`, which has a `.` as a trigger

**Comment by V-ed** [comment]
> you can try to disable `windicss.enableEmmetCompletion` in you VS Code settings, because this uses the `.` character as a trigger

![image](https://user-images.githubusercontent.com/16652915/118832642-cbdc2080-b88e-11eb-849a-3f98098b86e2.png)

Is this normal? :)

**Comment by V-ed** [comment]
Hold up, did the `windicss.enableEmmetCompletion` setting came out today? I had this issue yesterday but only made an issue about it today haha

Considering the `windicss.enableEmmetCompletion` setting was disabled when I updated, I did not have to chnage anything for this to be fixed, just needed to update the extension.

That was quick, thanks for the help!
