### ISSUE TITLE
The plug-in will make the label lose the original attribute prompt

### ISSUE THREAD

**Issue by jiangmaniu** [windicss/windicss-intellisense#139]
Sorry, my English is not good, the following content is translated by Google, if I am say  not clear, please forgive me

https://user-images.githubusercontent.com/50100681/118943504-4471d880-b986-11eb-8dda-1e064e3a72b0.mp4

It can be seen that when the plug-in is not used, the class attribute of the div tag has a prompt, but after opening the plug-in, the original attribute prompt will be replaced by the plug-in prompt. Can the plug-in prompt be shared with the original label prompt?

Remarks: If the tag does not have a class attribute prompt during development, every time you write the class of the tag, you need to write `class=""` completely, which will greatly affect my development efficiency. If prompted, I just need to write `Space + cl` and press enter.

This is the directory structure of my current test project：

![image](https://user-images.githubusercontent.com/50100681/118943693-6d926900-b986-11eb-8266-1e7f5070080d.png)

**Comment by voorjaar** [comment]
Thank you for bring two valuable issues, both of them should have been fixed in `v0.16.9`.
