### ISSUE TITLE
v0.17.0 breaks completion with typography plugin

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#144]
v0.17.0 breaks completion completly for me.. i am trying to find out why this happens...

/cc @voorjaar

**Comment by alexanderniebuhr** [comment]
seems to just breaks on svelte projects

**Comment by alexanderniebuhr** [comment]
UPDATE: it breaks on all languages ( i've tested html & svelte) one big project and one just simple one.

It breaks if an `windi.config` file with the typography plugin exists.. if this plugin is removed from config everything works as expected.. v0.16.x of intellisense works too. 
Not sure why it breaks.. no error thrown..

**Comment by voorjaar** [comment]
v0.17.1 should fix it. try it.

**Comment by alexanderniebuhr** [comment]
[v0.17.1](https://github.com/windicss/windicss-intellisense/releases/tag/v0.17.1) fixes this. correct 👍
