### ISSUE TITLE
duplicated prefix in completion

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#145]
```
module.exports = {
  prefix: "tw-",
  prefixer: true,
  theme: {
    extend: {
      colors: {
        'deep-blush': {
          '50': '#fef8fa',
          '100': '#fdf1f6',
          '200': '#fadce8',
          '300': '#f7c6d9',
          '400': '#f29cbd',
          '500': '#ec71a1',
          '600': '#d46691',
          '700': '#b15579',
          '800': '#8e4461',
          '900': '#74374f'
        }
      },
    },
  },
};
```
![image](https://user-images.githubusercontent.com/45965090/119254485-dbbd7280-bbb6-11eb-9bb3-f9cb7324f6da.png)

**Comment by voorjaar** [comment]
<img width="662" alt="Screen Shot 2021-05-23 at 17 32 57" src="https://user-images.githubusercontent.com/69119532/119255193-f8749d00-bbec-11eb-99c2-58f16ac4ce18.png">

Cannot be reproduced

**Comment by alexanderniebuhr** [comment]
closing.. seems that after I renewed the config file it fixed.. maybe some old cache..
