### ISSUE TITLE
Sorting Should Respect Newlines

### ISSUE THREAD

**Issue by han-tyumi** [windicss/windicss-intellisense#161]
I would like to enable `Sort On Save` but unfortunately there is a conflict when using Prettier.
Prettier wants long class attributes names' to be on separate lines but Windi will sort them back onto one line.
After saving it appears Windi's sorting is happening after Prettier leading to issues if you are also using ESLint with Prettier.

![image](https://user-images.githubusercontent.com/13040345/120958802-7628c480-c726-11eb-89d1-9bff2d6e46c4.png)
![image](https://user-images.githubusercontent.com/13040345/120958772-63ae8b00-c726-11eb-985e-adcc12e2bab8.png)

So one solution, if possible, could be to run the sorter before Prettier or other formatters.
However I think the better solution would be to respect the formatting when sorting class names.

**Comment by IgnisDa** [comment]
I would like to work on this. Will make a PR soon.

**Comment by alexanderniebuhr** [comment]
[v0.20.0](https://github.com/windicss/windicss-intellisense/releases/tag/v0.20.0)
