### ISSUE TITLE
'Sort on save' not working with css files

### ISSUE THREAD

**Issue by fliu2476** [windicss/windicss-intellisense#168]
Environment | Info
-- | --
WindiCSS IntelliSense | 0.18.3
vscode | 1.56.2
System | macos 11.4
Browser | google chrome

issue: 'Sort on save' not working.

**Comment by natasha1007** [comment]
test/test-ghe-restore.sh

**Comment by alexanderniebuhr** [comment]
please provide more information of your project and setup

**Comment by natasha1007** [comment]
dzimidrol5:main

**Comment by alexanderniebuhr** [comment]
should be fixed with newer version of the extension
