### ISSUE TITLE
Invasive

### ISSUE THREAD

**Issue by Zenthae** [windicss/windicss-intellisense#17]
is it possible to have the completion of windicss class only in class attribute or at list only in string ? because at the moment it's displayed everywhere and it's really invasive
![image](https://user-images.githubusercontent.com/32647899/109395432-a04f3700-792c-11eb-9b80-36292b95d733.png)

**Comment by alexanderniebuhr** [comment]
duplicate of https://github.com/windicss/windicss-intellisense/issues/2

will be fixed soon
