### ISSUE TITLE
Attributify with vite-plugin-icons

### ISSUE THREAD

**Issue by sainf** [windicss/windicss-intellisense#175]
There are some TS warnings when using the the the "vite-plugin-icons".

Attributify is fantastic, it improve by far the speed on reading the code!

![image](https://user-images.githubusercontent.com/1210947/122212670-07730600-cea0-11eb-94eb-43fdca79d7d6.png)

**Comment by alexanderniebuhr** [comment]
is this warning coming from windicss extension?

**Comment by sainf** [comment]
You are right, this info is from TS. Probably a vue/ts issue.

The vite-plugin-icon generates and "FunctionalComponent<SVGAttributes, {}>" and the Autocomplete in Classes and Attributify mode work's fine.

Sorry for the inconvenience
