### ISSUE TITLE
WindiCSS IntelliSense dont no support Autocomplete and more features

### ISSUE THREAD

**Issue by Klonuotas** [windicss/windicss-intellisense#188]
install, WindiCSS IntelliSense for VS code dont no support Autocomplete and more features?

My project: sveltekit + vite + typescript + Windicss

**Console log: Output**
Windi CSS Intellisense Is Now Active!

**My status:**

Version: 1.57.1 (user setup)
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Klonuotas** [comment]
All ok fix problem, rename file name from **tailwind.config.js** to windi.config.js and successfully run Autocomplete and all features..

**Comment by alexanderniebuhr** [comment]
can you provide more information what is not working?

**Comment by Klonuotas** [comment]
Installl WindiCSS IntelliSense for VS Code, does not display (Autocomplete) Intelligent suggestions for utilities and variants.. 

But deleting file **tailwind.config.js** all features starts working.. 
but in that case I will not have configuring Windi CSS file..

**Comment by alexanderniebuhr** [comment]
Do you have a repro for me to test? I cannot reproduce this issue, in my repos.

**Comment by Klonuotas** [comment]
before that was **module.exports = { ]** for windi.config.js and change to **export default defineConfig({ })**

and fix problem for WindiCSS IntelliSense..

but have more problem for this code.

written code inside class  **{enabled ? 'opacity-0' : 'opacity-100'}**  does not display (Autocomplete) for  WindiCSS IntelliSense but remove this code, all everything working for CSS for a class name by hovering over it.

**E.g for code:**

export let enabled = false;
const toggle = () => (enabled = !enabled);

`<span
   class="**{enabled
	? 'opacity-0'
	: 'opacity-100'}**  ease-in duration-200 absolute inset-0 h-full w-full flex items-center justify-center transition-opacity"
	aria-hidden="true"
>`

or not allowed written code inside class for {enabled ? 'opacity-0' : 'opacity-100'}?

**Comment by alexanderniebuhr** [comment]
`.svelte` files?

**Comment by alexanderniebuhr** [comment]
Look at the screenshot it works for me. Can you share your screenshot, or a minimal repro to clone?
![image](https://user-images.githubusercontent.com/45965090/124090187-e0e2cc80-da54-11eb-896a-599a5ac30509.png)
`windi.config.js`
![image](https://user-images.githubusercontent.com/45965090/124090206-e6d8ad80-da54-11eb-9805-32ad7d6ff0e5.png)

**Comment by Klonuotas** [comment]
I think the intellisense can't know that you are in a class context.

Repo for project:
[repo windi.config.js](https://github.com/munxar/sveltekit-tailwind/blob/main/windi.config.ts)

yes .svelte files

**Comment by alexanderniebuhr** [comment]
Only one bug with the inline template strings.. Will fix this. But it should work everywhere else

**Comment by alexanderniebuhr** [comment]
@Klonuotas check if https://github.com/windicss/windicss-intellisense/releases/tag/v0.19.1 fixes your problem?

**Comment by Klonuotas** [comment]
> @Klonuotas check if https://github.com/windicss/windicss-intellisense/releases/tag/v0.19.1 fixes your problem?

Thix all everything working.
