### ISSUE TITLE
autocomplete just on html attributes in svelte

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#2]
autocomplete is showing up even if not in class attribute, so every time I am writing `{`and `TAB` I am getting a windicss-intellisense class. Can post screenshots later :)

**Comment by voorjaar** [comment]
Yes. I found this too.

**Comment by voorjaar** [comment]
I guess that after the promotion tomorrow, issues will soon be overwhelmed here. 😂

**Comment by HeyImNoxz** [comment]
got the same bug

![image](https://user-images.githubusercontent.com/33727265/109389732-eea10d80-790d-11eb-9443-63c4225090b7.png)
