### ISSUE TITLE
How to stop suggestions from hiding Svelte component props?

### ISSUE THREAD

**Issue by dazzoh** [windicss/windicss-intellisense#213]
Hi,

I am not sure if this is a bug, but intellisense suggestions for properties on a svelte component are completely hidden by windi class names, which shouldn't even be an option - unless its attributify suggestions.

If this is intended, is there a way to disable it?

Thanks,
D

**Comment by alexanderniebuhr** [comment]
can you please add screenshots or a quick screencast?

**Comment by dazzoh** [comment]
Sure, see below - cursor is in the space where the arrow is pointing
![image](https://user-images.githubusercontent.com/12727405/127636097-9830fbbf-f049-4044-b1bc-6b622d2cda46.png)

**Comment by alexanderniebuhr** [comment]
Just pushed a fix. please try after it gets update in the marketplace and let me know

**Comment by dazzoh** [comment]
Awesome, thanks for the quick response this was driving me insane.

**Comment by dazzoh** [comment]
Thanks, the classes are gone, but the attributify options still show up above the props (it is disabled in my windi.config).  Thinking about it, they probably should not be showing in component prop options either as they are not props of the component and would have no effect.

**Comment by alexanderniebuhr** [comment]
for attributify there is a extension setting
https://github.com/windicss/windicss-intellisense/blob/main/package.json#L170
https://github.com/windicss/windicss-intellisense/blob/main/package.json#L175

**Comment by dazzoh** [comment]
Thanks, that works for components, but now also disables it on native elements (not that I am using attributify so I'm OK with this) - Others might not be, so perhaps worth re-opening.
