### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by IgnisDa** [windicss/windicss-intellisense#216]
Currently, this extension does not support monorepos, ie, if the `windi.config.ts` is a sub-directory. Can support for this be added?

**Comment by alexanderniebuhr** [comment]
Thank you for your proposal.
These support feature could be added for sure, there already might be some logic in our vite integration plugin for monorepos.

**Comment by IgnisDa** [comment]
Hello @alexanderniebuhr I would like to work on this.

**Comment by IgnisDa** [comment]
Found a bug in the current implementation which breaks the extension.

![image](https://user-images.githubusercontent.com/60938164/129514706-c3b59cc2-5b8e-4bc6-94f7-2b8b5fb4fdc6.png)

Will make a PR to fix this.
