### ISSUE TITLE
Autocompletion isn't working in pug file

### ISSUE THREAD

**Issue by jd-0001** [windicss/windicss-intellisense#242]
I am not getting windiCSS autocompletion when using pug in vscode :thinking: 

Steps:
1. Create new project `pnpm exec create-vite windi-int --template vanilla-ts`
2. add windi & pug: pnpm add vite-plugin-windicss windicss pug-cli
3. Install WindiCSS IntelliSense extension
4. add vscode config:
5. Add vite config & windi import in main file according to docs: https://windicss.org/integrations/vite.html#install

{
    "windicss.enableEmmetCompletion": true,
    // Below setting is not working I guess. I don't know if this is even required or not
    "windicss.includeLanguages": {
        "*.pug": "html"
    }
}

// vite.config.ts
import WindiCSS from 'vite-plugin-windicss'

export default {
  plugins: [
    WindiCSS(),
  ],
}

// main.ts

import 'virtual:windi.css'
import './style.css'

With this setup if I type .h in HTML file I am getting autocompletion but in .pug file with .h I am not getting autocompletion :thinking: 

What I am missing here.

Regards.

**Comment by jd-0001** [comment]
Hi @alexanderniebuhr I tried that but it isn't working.

However, if we use file association config:

```
"files.associations": {
    "*.pug": "html"
  },
```

it shows suggestions but I lost pug features like syntax highlighting

**Comment by jd-0001** [comment]
Do you want me to provide GitHub repo?

I am happy to create one for you.

**Comment by alexanderniebuhr** [comment]
it would be great to get a very simple one pls

**Comment by jd-0001** [comment]
Hi @alexanderniebuhr 

Here's the repo: https://github.com/jd-0001/windi-autocompletion-issue

and steps are mentioned in readme.

Regards.

**Comment by jd-0001** [comment]
Can we now remove the label "needs reproduction"?

**Comment by alexanderniebuhr** [comment]
@jd-0001 ok i can reproduce it now. Have to look into it in more detail to find a fix

**Comment by alexanderniebuhr** [comment]
@jd-0001 

ok I was pretty stupid. the language identifier is `jade` not `pug`
so, this config should work.

```json
    "windicss.includeLanguages": {
        "jade": {
            "type":"html",
            "patterns": [
                "(\\s+class(Name)?\\s*=\\s*{?\\s*[\"'`])[^\"'`]*$"
            ]
        }
    },
```

**Comment by jd-0001** [comment]
Hi, @alexanderniebuhr Have you tried that?

I updated `settings.json` according to provided snippet but the result is the same.

**Comment by alexanderniebuhr** [comment]
Yea I have tried it with the jade config and the latest update.

**Comment by jd-0001** [comment]
Hi @alexanderniebuhr 

Sorry to say but I updated the settings according to your snippet as shown in the below commit: https://github.com/jd-0001/windi-autocompletion-issue/commit/e6cbe6fd3ce1db89095ae83e9a727437c9c7d29d but still autocompletion isn't working in `.pug` file :thinking: 

I am also using the latest VSCode release and uninstalled & reinstalled `windicss-intellisense` extension.

As I have updated the settings in the sample repo, can you test it once again?

Regards.

**Comment by alexanderniebuhr** [comment]
'div(class="bg-' works for me.
If you need any other syntax to autocomplete, you need to add a custom pattern!

**Comment by alexanderniebuhr** [comment]
@jd-0001 sorry the release of yesterday version v0.21.2 was not published. It should work with that version. Also, I think you can try to change the pattern to:

```
"patterns": [
    "(\\s*class(Name)?\\s*=\\s*{?\\s*[\"'`])[^\"'`]*$",
    "\\.\\S*$"
]
```

**Comment by jd-0001** [comment]
Hey @alexanderniebuhr It's working with your latest patterns :heart_eyes: 

For others below is full config as I will remove the repo from my github.

```json
{
    "editor.quickSuggestions": {
        "strings": true
    },
    "windicss.enableEmmetCompletion": true,
    "windicss.includeLanguages": {
        "jade": {
            "type": "html",
            "patterns": [
                "(\\s*class(Name)?\\s*=\\s*{?\\s*[\"'`])[^\"'`]*$",
                "\\.\\S*$"
            ]
        }
    },
}
```

Thanks for taking the time to look into this.

I really appreciate that. :blush:
