### ISSUE TITLE
Add support for rescript

### ISSUE THREAD

**Issue by jamessouth** [windicss/windicss-intellisense#246]
Hello, can support for `rescript` (`.res` files) be added? I tried the `includeLanguages` option 
```json
"windicss.includeLanguages": {
     "res": "html"
}
```
including with the `type` and `pattern` keys, but it's not working. [Here is the TW PR](https://github.com/tailwindlabs/tailwindcss-intellisense/pull/222). 

Thank you!

**Comment by alexanderniebuhr** [comment]
Have you checked that 'res' is the language identifier for rescript

**Comment by alexanderniebuhr** [comment]
try v0.21.3

**Comment by jamessouth** [comment]
This works on v0.21.3:
```json
"windicss.includeLanguages": {
        "rescript": "html"
}
```


Thank you!

**Comment by XiNiHa** [comment]
That config is not working for me (v0.21.4)
I'm pretty sure that you're also using `@rescript/react`.
Is there any additional info needed to investigate the issue?
