### ISSUE TITLE
Windi css intellisense is too eager 

### ISSUE THREAD

**Issue by louiss0** [windicss/windicss-intellisense#273]
Windi css intellisense makes to many assumptions about the css code that I'm writing. The picture's below are meant to show that even though I'm not using the animation plugin i get autocomplete for it. tailwind css intellisense uses the config file to figure out what classes are available then uses those in autocomplete.  This way I don't get any strange assumptions about the classes that are being used in the project. Please do the same for windi   

![2021-10-29 (1)](https://user-images.githubusercontent.com/29028601/139476053-87d5f77c-fcbe-4955-a6be-a9f2d899b8a4.png)

![2021-10-29 (2)](https://user-images.githubusercontent.com/29028601/139476068-cb312ce8-cd7f-480f-8d21-bba06ef74af6.png)

**Comment by alexanderniebuhr** [comment]
We probably change the way plugins work with windi v4. Once that is done (coming soon), don't have the problem anymore.

**Comment by oalrbabaa** [comment]
> Windi css intellisense makes to many assumptions about the css code that I'm writing. The picture's below are meant to show that even though I'm not using the animation plugin i get autocomplete for it. tailwind css intellisense uses the config file to figure out what classes are available then uses those in autocomplete.  This way I don't get any strange assumptions about the classes that are being used in the project. Please do the same for windi   
> 
> 
> 
> 
> 
> ![2021-10-29 (1)](https://user-images.githubusercontent.com/29028601/139476053-87d5f77c-fcbe-4955-a6be-a9f2d899b8a4.png)
> 
> 
> 
> ![2021-10-29 (2)](https://user-images.githubusercontent.com/29028601/139476068-cb312ce8-cd7f-480f-8d21-bba06ef74af6.png)
> 
> 
> 
> 

![image](https://github.com/windicss/windicss-intellisense/assets/88998851/fe8c0869-adf4-4377-aa2f-0c9486c653ad)

**Comment by louiss0** [comment]
> > Windi css intellisense makes to many assumptions about the css code that I'm writing. The picture's below are meant to show that even though I'm not using the animation plugin i get autocomplete for it. tailwind css intellisense uses the config file to figure out what classes are available then uses those in autocomplete.  This way I don't get any strange assumptions about the classes that are being used in the project. Please do the same for windi
> > ![2021-10-29 (1)](https://user-images.githubusercontent.com/29028601/139476053-87d5f77c-fcbe-4955-a6be-a9f2d899b8a4.png)
> > ![2021-10-29 (2)](https://user-images.githubusercontent.com/29028601/139476068-cb312ce8-cd7f-480f-8d21-bba06ef74af6.png)
> 
> ![image](https://user-images.githubusercontent.com/88998851/265551071-fe8c0869-adf4-4377-aa2f-0c9486c653ad.jpeg)



> > Windi css intellisense makes to many assumptions about the css code that I'm writing. The picture's below are meant to show that even though I'm not using the animation plugin i get autocomplete for it. tailwind css intellisense uses the config file to figure out what classes are available then uses those in autocomplete.  This way I don't get any strange assumptions about the classes that are being used in the project. Please do the same for windi
> > ![2021-10-29 (1)](https://user-images.githubusercontent.com/29028601/139476053-87d5f77c-fcbe-4955-a6be-a9f2d899b8a4.png)
> > ![2021-10-29 (2)](https://user-images.githubusercontent.com/29028601/139476068-cb312ce8-cd7f-480f-8d21-bba06ef74af6.png)
> 
> ![image](https://user-images.githubusercontent.com/88998851/265551071-fe8c0869-adf4-4377-aa2f-0c9486c653ad.jpeg)

I think you should migrate to UnoCSS this issue will never be solved. https://unocss.dev/
