### ISSUE TITLE
Feature Request: Don't do intellisense when confg file is not there.

### ISSUE THREAD

**Issue by hanayashiki** [windicss/windicss-intellisense#279]
This library is great job!

I'm opening a new project without windicss setup, but it gives me intellisense nevertheless. I had to disable windicss globally. I think we should use similar policy like eslint and tailwindcss, not to enable the plugin unless the user is explicitly using it.

**Comment by alexanderniebuhr** [comment]
I am working on a fix for this. You can try experimental state if the new `pre-release` version of the extension.
