### ISSUE TITLE
Is there a CLI version for sorting classes?

### ISSUE THREAD

**Issue by smac89** [windicss/windicss-intellisense#283]
I was using rustywind, but it tends to break when it comes to downloading the rust binaries, and this was affecting my CI process.

Does this package come with a class sorter, which can be turned into a package? I'm just trying to delay the inevitable which is to write my own tailwind/windicss class-sorter

**Comment by alexanderniebuhr** [comment]
you can also track https://github.com/alexanderniebuhr/prettier-plugin-unocss (which I would call the windi css version)
