### ISSUE TITLE
Sort on save removes classes on save

### ISSUE THREAD

**Issue by stctheproducer** [windicss/windicss-intellisense#284]
I have an element using the `before:` modifier but every time my file gets saved, the class is changed from:

```html
<li v-for="(user, index) in users" :key="index" class="py-1 pl-2 before:content-['\2022']" v-html="user.name"></li>
```

to

```html
<li v-for="(user, index) in users" :key="index" class="py-1 pl-2 '\2022']" v-html="user.name"></li>
```

Is there a configuration I am missing?

**Comment by alexanderniebuhr** [comment]
Does this also happen with out an arbitrary value like `-[...]`?

**Comment by motea927** [comment]
I have this problem too, `before:(content-['|'] block ml-2 text-xl order-1)` wii  change to `'|'] block ml-2 text-xl order-1)`

**Comment by stctheproducer** [comment]
> Does this also happen with out an arbitrary value like `-[...]`?

No, the bug only occurs when there's arbitrary value.

**Comment by alexanderniebuhr** [comment]
you can also track https://github.com/alexanderniebuhr/prettier-plugin-unocss (which I would call the windi css version)
