### ISSUE TITLE
Intellisense Plugin fails with due to node: prefixes

### ISSUE THREAD

**Issue by rxmii4269** [windicss/windicss-intellisense#288]
Upon starting vscode the plugins fails and logs the runtime statuses listed below:

- Cannot find module 'node:fs' Require stack: - /home/romainemurray/tweeter-ui-nuxt3-test/node_modules/gzip-size/index.js

- Illegal value for `line`

- Cannot find module 'node:fs' Require stack: - /home/romainemurray/tweeter-ui-nuxt3-test/node_modules/gzip-size/index.js

Manually going into each of these paths and removing the "node:" prefixes and reloading the window actually allows the plugin to work as intended. 

![image](https://user-images.githubusercontent.com/49266906/147594102-073cd2ce-da25-4e05-94b7-bc579f541418.png)

**Comment by alexanderniebuhr** [comment]
@rxmii4269 we actually don't have any `node:` prefixed imports in our extension. Not sure why you get this errors
