### ISSUE TITLE
code folding didn't update after paste text

### ISSUE THREAD

**Issue by voorjaar** [windicss/windicss-intellisense#29]
### Before

![Screen Shot 2021-03-01 at 18 40 30](https://user-images.githubusercontent.com/69119532/109486305-a9234280-7abd-11eb-96bc-458fdf142e60.png)

### After
![Screen Shot 2021-03-01 at 18 28 10](https://user-images.githubusercontent.com/69119532/109486314-ab859c80-7abd-11eb-98ec-f96419b13936.png)

**Comment by alexanderniebuhr** [comment]
is `<path fill-rule="evenodd" d="M10 18a8 8 ..." clip-rule="evenodd" />` because of our extension? If yes, this is not expected and also a bug

**Comment by voorjaar** [comment]
> is `<path fill-rule="evenodd" d="M10 18a8 8 ..." clip-rule="evenodd" />` because of our extension? If yes, this is not expected and also a bug

Yes. compare two pictures. You can find the problem. That is the folding left by the className in the previous state.

**Comment by alexanderniebuhr** [comment]
@voorjaar can you test with latest release, for mee it seems to work now. However performance is bad
