### ISSUE TITLE
Question : Hide multiple syntaxes for variants

### ISSUE THREAD

**Issue by Miaourt** [windicss/windicss-intellisense#3]
Hello,

Wondered if there was a config to not have both the `CamelCase `and `snake-case` version of the autocomplete.

And maybe only suggest by default the `snake-case` version of it, which seems more consistent among TailwindCSS classes.

![Screenshot of the intellisense dropdown suggesting me both blue-gray and blueGray](https://user-images.githubusercontent.com/1571367/109194852-20916300-779a-11eb-8e63-6abcf79aa351.png)

**Comment by voorjaar** [comment]
Yes, this is a bug in windicss. I was lazy and didn't delete the CamelCase. It will be resolved when the next version is released.

**Comment by alexanderniebuhr** [comment]
tagging this as `wontfix` since this issue will be closed with next windicss release, just for better tracking. Does not mean we are not working on it

**Comment by Zenthae** [comment]
@alexanderniebuhr should probably get closed since it was fixed in past release

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/49c57f44d0658a0fbada69797d797e720ec03f2c fix this
