### ISSUE TITLE
Adapt `prettier-plugin-tailwindcss` for Windi

### ISSUE THREAD

**Issue by essarn** [windicss/windicss-intellisense#302]
Found out that Tailwind has released a neat prettier plugin for class sorting: https://github.com/tailwindlabs/prettier-plugin-tailwindcss 

Are there any plans to adapt it to work with Windi? In my option, it seems like a great idea since the current sorting solution has some problems like #297. There is work needed to support Windi specific features like variant groups, but it shouldn't be too hard.

I'm open to trying this if there isn't anything planned.

**Comment by alexanderniebuhr** [comment]
Feel free to contribute a PR.

**Comment by alexanderniebuhr** [comment]
you can also track https://github.com/alexanderniebuhr/prettier-plugin-unocss (which I would call the windi css version)
