### ISSUE TITLE
performance audit

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#32]
will do some analysis and track stuff here

**Comment by alexanderniebuhr** [comment]
actually, i do not think we have any performance issue at all for v1 ... function is running under 2ms

![performanceAuditv1](https://user-images.githubusercontent.com/45965090/109983546-34d9e080-7d03-11eb-9cf0-c41d14485eee.png)

**Comment by voorjaar** [comment]
The preloading time is very long. When multiple interfaces are opened at the same time, the initialization time will burst.

For the solution, we generate a cache of complements before release, and only those completions with modified configurations are loaded when the user loads, which can effectively reduce the initialization time.

**Comment by alexanderniebuhr** [comment]
Yes we could do that :)
