### ISSUE TITLE
support .ts config files

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#38]
see
https://github.com/windicss/windicss-intellisense/issues/33
https://github.com/windicss/windicss-intellisense/issues/24

**Comment by alexanderniebuhr** [comment]
@voorjaar is this closed with v0.4.0?

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss-intellisense/commit/22943eb587f67fa01d88fbf2a64f78a742c1de88 support this.
