### ISSUE TITLE
 [Vscode extension] custom component  shouldn't start with .

### ISSUE THREAD

**Issue by cereschen** [windicss/windicss-intellisense#44]
![image](https://user-images.githubusercontent.com/52478109/110241196-7a5c0f00-7f8a-11eb-84c0-078c567a6c85.png)

**Comment by alexanderniebuhr** [comment]
just for my understanding as I do not know how components work, why can't you just name them without dot in the config?

**Comment by cereschen** [comment]
> 只是出于我的理解，因为我不知道组件的工作原理，为什么您不能在配置中不加点命名呢？

I just did the same thing as tailwind
https://tailwindcss.com/docs/plugins#adding-components

**Comment by alexanderniebuhr** [comment]
Ok I understand!
If you have an Idea how to fix, a PR would be highly welcome.
