### ISSUE TITLE
[Pre-Release] Extension did not activate on any monorepo project (PNPM, Rush, Lerna)

### ISSUE THREAD

**Issue by evamass** [windicss/windicss-intellisense#453]
Seems like extension was broken in pre-release versions when in `package.json` was added some extraordinaries `activationEvents`.

Monorepo projects often does not have `node_modules` in root of project to prevent shadow dependencies, so I think there a very bad practice to choose for users when extension should be enabled or not. Any VS-code users have option to disable extension per Workspaces if he need.

@alexanderniebuhr , please, add more flexible `activationEvents` or special config for force activate this extension or revert any changes to last release variant.

**Comment by Tanimodori** [comment]
Same issue here. The pre-release version stop working on a rush monorepo project. Any commands cannot be found.

**Comment by Tanimodori** [comment]
in https://github.com/windicss/windicss-intellisense/commit/75ac27c98c7cf782a24829d2b7b0610ff75e6bf7

```diff
  "activationEvents": [
-    "workspaceContains:**/node_modules/windicss/*",
-    "workspaceContains:**/node_modules/vite-plugin-windicss/*",
-    "workspaceContains:**/node_modules/rollup-plugin-windicss/*",
-    "workspaceContains:**/node_modules/windicss-webpack-plugin/*",
-    "workspaceContains:**/node_modules/nuxt-windicss/*",
-    "workspaceContains:**/node_modules/svelte-windicss-preprocess/*",
-    "workspaceContains:**/node_modules/stencil-windics/*s"
+    "workspaceContains:node_modules/windicss/package.json",
+    "workspaceContains:node_modules/vite-plugin-windicss/package.json",
+    "workspaceContains:node_modules/rollup-plugin-windicss/package.json",
+    "workspaceContains:node_modules/windicss-webpack-plugin/package.json",
+    "workspaceContains:node_modules/nuxt-windicss/package.json",
+    "workspaceContains:node_modules/svelte-windicss-preprocess/package.json",
+    "workspaceContains:node_modules/stencil-windics/package.json"
  ],
```

@alexanderniebuhr Please revert this. It is unusable in monorepo.

**Comment by alexanderniebuhr** [comment]
@Tanimodori that is an hard tradeoff. People complain if we activate on `*`, they complain if we activate on `windi.config` file.
Therefore this one is the best middle-ground. If I understand correctly, latest non pre-release version work? Why not using that?

Additionally you can make an PR which changes the activationEvents with all the limits outlined in the first sentence.

**Comment by Tanimodori** [comment]
If they don't want unnecessary startup they can disable this plugin (globally or per workspace) as mentioned by evamass. I don't think we should detect `node_modules` to control `activationEvents`. Another example is that I just want to make a quick fix on some repository, where install node modules is not required. By detecting `node_modules` it will prevent windicss-intellisense from startup.

**Comment by Tanimodori** [comment]
I've encountered #353 in prod version and just want to try the alpha.

**Comment by Tanimodori** [comment]
Thank you for merging! Let's wait until v0.23.6 gets released into the plugin market!

**Comment by alexanderniebuhr** [comment]
Actually waiting for someone to add a new PAT.. I do not have the permission to do that.

**Comment by Tanimodori** [comment]
When will v0.23.6 get released on the marketplace? It's been a month since this patch was merged...

**Comment by alexanderniebuhr** [comment]
Once someone with access to the account will update the token... I've pinged them multiple times... nothing I can do..
