### ISSUE TITLE
Doesn't work when using custom dynamic utilities

### ISSUE THREAD

**Issue by mkhennoussi** [windicss/windicss-intellisense#47]
Hi guys ! Thanks for your work ! Windicss "freedom" is really cool and this extension helps a lot !

I've noticed when I use a custom dynamic utility like in the documentation of the config file : 
```
 plugin(function({ addDynamic, variants }) {
      addDynamic("skew", ({ Utility, theme }) => {
        return Utility.handler
          .handleStatic(theme("skew"))
          .handleNumber(0, 360, "int", (number) => `skewY(-${number}deg)`)
          .createProperty('transform');
        }, variants('skew'));
}),
```
the extension stops working.
Any ideas why ? 

Thanks !

**Comment by alexanderniebuhr** [comment]
cc @voorjaar

**Comment by voorjaar** [comment]
Well, this is the expected behavior, because it is dynamically generated, so the possibilities are infinite, so it is necessary to add docs for the dynamic plugin, so that plugin can load completion stuff. We haven't added this interface yet, please wait a moment.

**Comment by voorjaar** [comment]
From windicss v3.0.11 & extension v0.17.2 you can add `completions` option to api. please reference our official plugins

https://github.com/windicss/windicss/blob/main/src/plugin/line-clamp/index.ts#L18-L21 

so for your case:

```js
plugin(function({ addDynamic, variants }) {
  addDynamic("skew", ({ Utility, theme }) => {
    return Utility.handler
      .handleStatic(theme("skew"))
      .handleNumber(0, 360, "int", (number) => `skewY(-${number}deg)`)
      .createProperty('transform');
    }, {
      group: 'skew',
      completions: [
        'skew-{static}',
        'skew-{int}',
      ],
      variants: variants('skew')
    });
}),
```
