### ISSUE TITLE
An LSP?

### ISSUE THREAD

**Issue by yassinebridi** [windicss/windicss-intellisense#48]
This project looks pretty interesting, and i would love to start using it.
I don't know if you have plans to add support for an [LSP](https://microsoft.github.io/language-server-protocol/), as it would add support for virtually any other text editor.
Tailwind already have [support](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/tailwindcss-intellisense/src/lsp/server.ts) for this.
I wonder if the same code can be done for windicss

**Comment by voorjaar** [comment]
Good idea. I think we should support it eventually, but not a first priority job for now.

**Comment by alexanderniebuhr** [comment]
I think a first approach to an LSP is already added. If you have any further ideas and proposal, please open new issues.
