### ISSUE TITLE
support class sorting for not native HTML attributes & syntax

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#52]
`<div class="{localStorage.theme === 'dark' ? 'dark' : 'light'} flex flex-col min-h-100vh overflow-y-hidden">`

to be fixed in
https://github.com/windicss/windicss-intellisense/blob/3c9b378a4d6269cf9a26797e53382cdbe2f84176/src/utils/filetypes.ts#L1-L5

**Comment by antfu** [comment]
```js
/class=(["'])([^\1]*$)/; 
```

This might work, but you will need to also change the matching group

**Comment by alexanderniebuhr** [comment]
not quite sure that it works.. we also need to make sure that other attributes to not get matched, like below.. target should not auto complete.. just class & className & variants defined
(i have not completed the lines, since the regex will always match to cursor position with `$`)

```svelte
<div class="{localStorage.theme === 'dark' ? 'dark' : 'light'} flex min-h-100vh overflow-y-hidden flex-col ...
<div class="flex min-h-100vh overflow-y-hidden flex-col" target=" ....
<div class="flex min-h-100vh overflow-y-hidden hover:(bg-white)" ....
```

**Comment by antfu** [comment]
Oh then change back to $, I thought it was full match

**Comment by alexanderniebuhr** [comment]
do not have a solution yet.. not highest prio

**Comment by alexanderniebuhr** [comment]
vue #57

**Comment by alexanderniebuhr** [comment]
https://github.com/windicss/windicss-intellisense/commit/f586a0be5b3e067aa0a0e69102c975c548a3087f
#78
