### ISSUE TITLE
Sort on save breaking condition condition on vue templates

### ISSUE THREAD

**Issue by pikax** [windicss/windicss-intellisense#57]
Version: v0.6.3

When you save a ternary operation:
```html
<html>
  <input
    :checked="isCheckbox ? value : undefined"
  />
</html>
<!-- becomes -->
<template>
  <input
    :checked="? isCheckbox value : undefined"
  />
</template>
```

**Comment by alexanderniebuhr** [comment]
waiting on upstream fix
https://github.com/windicss/windicss/issues/213

**Comment by alexanderniebuhr** [comment]
https://github.com/windicss/windicss-intellisense/blob/814024ff517fa6bc72d9b50dd76182a68c3379b6/src/utils/parser.ts#L9
