### ISSUE TITLE
Show/ hide short cut for CSS

### ISSUE THREAD

**Issue by IRediTOTO** [windicss/windicss-intellisense#59]
Hi, let's look at Gif below, i know it will be helpfull to read, but sometime i need it show all up. Is there any setting to turn off this feature? I hope can get an shortcut to show hide long codes. THank you
![image](https://user-images.githubusercontent.com/15695252/112743662-6d4ba200-8fc3-11eb-9512-e987f0b42bab.png)
https://i.imgur.com/wyU0SOG.gif

**Comment by alexanderniebuhr** [comment]
setting in vs code is `windicss.enableCodeFolding`
