### ISSUE TITLE
improve order to show utillities without a value (base) higher than once with value

### ISSUE THREAD

**Issue by Zenthae** [windicss/windicss-intellisense#61]
would it be possible to have the order reversed for properties like that ? I only have those to as an example, (i don't know if it the same other) but i believe that most of the time people want `flex-grow & flex-shrink` over `flex-grow-0 & flex-shrink-0`
![image](https://user-images.githubusercontent.com/32647899/112908737-58b8f800-90f0-11eb-8cf7-14566ded82e9.png)
![image](https://user-images.githubusercontent.com/32647899/112908762-6a020480-90f0-11eb-984b-b5693e21d50f.png)

**Comment by ThaddeusJiang** [comment]
@alexanderniebuhr I am trying to improve this.

**Comment by ThaddeusJiang** [comment]
Hi @Zenthae 
Do you mean the completion suggestion?

![CleanShot 2021-04-05 at 22 14 26@2x](https://user-images.githubusercontent.com/17308201/113577481-4c86ea80-965c-11eb-9767-956964c4feda.jpg)

I have checked the completion logic and Windi CSS docs.

Summary:

- `flex-grow-0` higher than `flex-grow` in Windi CSS, [ref](https://windicss.org/utilities/flexbox.html#flex-grow).
- Our intellisense just flow the Windi CSS sort.

Is it make sense to you?

cc @alexanderniebuhr

**Comment by alexanderniebuhr** [comment]
@ThaddeusJiang not quite. completions are sorted in vs code extension.. see `completion.ts -> item.sortText` you can hook into their and tweak sort-text so it does get order right

**Comment by ThaddeusJiang** [comment]
@alexanderniebuhr I see.

One question, Should we tweak sort-text for only 4 classname?

**Comment by Zenthae** [comment]
> Hi @Zenthae
> Do you mean the completion suggestion?
> 
> ![CleanShot 2021-04-05 at 22 14 26@2x](https://user-images.githubusercontent.com/17308201/113577481-4c86ea80-965c-11eb-9767-956964c4feda.jpg)
> 
> I have checked the completion logic and Windi CSS docs.
> 
> Summary:
> 
> * `flex-grow-0` higher than `flex-grow` in Windi CSS, [ref](https://windicss.org/utilities/flexbox.html#flex-grow).
> * Our intellisense just flow the Windi CSS sort.
> 
> Is it make sense to you?
> 
> cc @alexanderniebuhr

yes, i'm talking about the completion suggestion, because like i said, i believe that most of the time, what people use is `flex-grow & flex-shrink` over `flex-grow-0 & flex-shrink-0`

**Comment by alexanderniebuhr** [comment]
I think we could make a rule. If an utility exist without number it has to be ordered first.. if It only exist with numbers order like before.
This would make sure that margin or padding kept correct 

@ThaddeusJiang maybe sort first then order by string lengths

**Comment by ThaddeusJiang** [comment]
OK, I see.

**Comment by alexanderniebuhr** [comment]
just going to close since there was no much activity lately, if some issue still exists please reopen a new issue
