### ISSUE TITLE
Add support for other templating languages

### ISSUE THREAD

**Issue by Princesseuh** [windicss/windicss-intellisense#71]
Hi!

I use Windi with [Eleventy](https://www.11ty.dev/) and so I use [Nunjucks templates](https://mozilla.github.io/nunjucks/). This works well, no issues about it. Even though there's no official support for it (yet?) this works completely fine, every features including the analyzer works perfectly

However, this extension doesn't work on .njk files even though they're (mostly) normal html files due to it only triggering on .html, .vue etc files. Changing the extension manually to make it so it enables itself on .njk files (adding them to package.json and filetypes.ts like php files are) works perfectly. However, of course this breaks whenever the extension is updated

I was wondering if a way to add it to other file formats without having to hack the extension would be possible. For instance, [vscode-auto-close-tag](https://github.com/formulahendry/vscode-auto-close-tag) allows this through a parameter called `auto-close-tag.activationOnLanguage` another reference might be the official emmet settings for doing so `emmet.includeLanguages`

Please note that I'm not asking for Nunjucks support to be added, VS Code doesn't even support them by default. I'm asking for a way to support file types arbitrarily 😅

**Comment by alexanderniebuhr** [comment]
good idea. do you feel making a PR?

**Comment by Princesseuh** [comment]
Unfortunately I really don't know much about VS Code extensions, the modifications needed to make .njk files works were pretty easy (essentially changing two JSON).

I'm afraid I wouldn't even know where to start to full on support file types arbitrarily 😅 I'm guessing also that some parts might be related to how the extension parse files? It should probably works like the official emmet settings does, as in it associate a new language to a supported one from a list using this format:

![image](https://user-images.githubusercontent.com/3019731/113487358-a2ee0080-9485-11eb-89e7-fc3448076c21.png)

**Comment by alexanderniebuhr** [comment]
ok no problem, I will do it then. make take some time :)

**Comment by alexanderniebuhr** [comment]
@Princesseuh just working on this feature. can you tell me which json you changed to make it work?

**Comment by Princesseuh** [comment]
@alexanderniebuhr Hey, for my quick fix I edited package.json (added an onLanguage for Nunjucks) and filetype.ts

> I have an solution, but seems that VS Code is recognize njk as plain text, do i need an additional extension for VS Code + njk

Yeah, Nunjucks isn't recognized by default, I'm using this extension: https://marketplace.visualstudio.com/items?itemName=eseom.nunjucks-template#overview

With this PR https://github.com/eseom/nunjucks-template/pull/28 because of a recent issue breaking syntax highlighting

**Comment by alexanderniebuhr** [comment]
ok cool.. i will have this feature ready for next release :)

**Comment by alexanderniebuhr** [comment]
edit
