### ISSUE TITLE
Add language specific destination for compiling commands

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#8]
compile is replace classes in compilation mode correctly, however does not add the styles to `<style></style>` tag..

Am I misunderstanding the function?

**Comment by Miaourt** [comment]
Maybe more an issue for https://github.com/windicss/svelte-windicss-preprocess ?

**Comment by alexanderniebuhr** [comment]
yeah I am currently contributing to it :) :D But I need to understand how this function is supposed to work. So I know what to push on the svelte repo :)

**Comment by alexanderniebuhr** [comment]
ok think. I got it, it should write a `windi.css` file. This works. So I am changing this to an enhancement, that we could implement that the language knows what language file it is in, and then puts the generated css in the appropriate place. But tbh this more a nice to have, than a must have. Still tracking it here...
