### ISSUE TITLE
Hover preview fails on last @apply style ending in ;

### ISSUE THREAD

**Issue by qgates** [windicss/windicss-intellisense#80]
Example:
```
body {
  @apply bg-gray-200 dark:bg-gray-600;
}
```
Hover over bg-gray-200 and we get a preview, but hover over bg-gray-600 and we don't.

**Comment by alexanderniebuhr** [comment]
hello, can you confirm it happens because of the `;`, or does it happen because, `bg-gray-600` is a `dark:` color

**Comment by antfu** [comment]
Confirmed it happens with `;` ending, and works if a space is inserted
