### ISSUE TITLE
Sorting doesn't work with state variants

### ISSUE THREAD

**Issue by gustavopch** [windicss/windicss-intellisense#93]
# Problem

Sorting works fine with:
```svelte
<button class="bg-red-500 cursor-pointer">Test</button>
```

but doesn't work as soon as a state variant is used (`focus:` in this case):
```svelte
<button class="bg-red-500 cursor-pointer focus:bg-red-900">Test</button>
```

# Expected behavior

Sorting should still work when there's a state variant. So `cursor-pointer` should be placed before `bg-red-500`.

# Actual behavior

Sorting simply stops working for the element that uses state variants, so `cursor-pointer` is not moved.

# Steps to Reproduce

1. Clone the repository: https://github.com/gustavopch/repro-windicss-sort-state-variants
2. Ensure you have the [WindiCSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=voorjaar.windicss-intellisense) VS Code extension installed
3. Open `src/App.svelte` in VS Code
4. Run `Windi CSS: Sort Utilities`
5. Observe that the classes were not sorted in the element that uses a state variant

# Environment

OS: Arch Linux
VS Code: 1.54.3
WindiCSS IntelliSense: 0.8.3
Dependencies: [Repro's package.json](https://github.com/gustavopch/repro-windicss-sort-state-variants/blob/master/package.json)

**Comment by alexanderniebuhr** [comment]
what do you mean by `doesn't work` ^^

**Comment by gustavopch** [comment]
@alexanderniebuhr Done :)

**Comment by alexanderniebuhr** [comment]
@gustavopch can you share a minimal repo?

**Comment by gustavopch** [comment]
@alexanderniebuhr Done. Just realized that the color also doesn't appear next to `bg-red-500` in the element that uses a state variant. It's like the extension can't even parse the classes.
![image](https://user-images.githubusercontent.com/10941958/115309697-03966200-a143-11eb-8681-e5b4d408628a.png)

**Comment by alexanderniebuhr** [comment]
@gustavopch are you sure on the latest update? this is how your repo looks if i open it just after clone

![image](https://user-images.githubusercontent.com/45965090/115399542-9d641a80-a1e8-11eb-9d41-43bc88c37557.png)

**Comment by gustavopch** [comment]
@alexanderniebuhr Hm, apparently not. The issue happened on VS Code v1.54.3 + WindiCSS IntelliSense v0.8.3. I've just updated to VS Code v1.55.2 + WindiCSS IntelliSense v0.11.5 and it seems to work fine. So I'm closing the issue. Thank you.

**Comment by alexanderniebuhr** [comment]
Yea we had issues with VS Code pre 1.55 and Intellisense pre 0.10.. sorry for that issue. Happy that it works now!
