### ISSUE TITLE
Auto Completion for variant is broken

### ISSUE THREAD

**Issue by Zenthae** [windicss/windicss-intellisense#94]
it looks like IntelliSense is broken after using variant, it's the same for every variants, and whether it's grouped or not
![yooJfPkop2](https://user-images.githubusercontent.com/32647899/115155795-c027ef00-a081-11eb-8aca-213c1ec69cd3.gif)

**Comment by MaxKarpyza** [comment]
if installed plug-ins 
    Auto Rename Tag or SCSS Everywhere

**Comment by alexanderniebuhr** [comment]
it does work without the plugins installed. So not sure what to do, seems that `Auto Rename Tag` & `SCSS Everywhere` inject in the completion handler here

**Comment by Zenthae** [comment]
indeed, disabling Auto Rename Tag fixed the issue, i juste hope that someone, one day, will fix that, because i don't know anything about extension dev, so i can't help here

**Comment by alexanderniebuhr** [comment]
you can disable `Auto Rename Tag` and use native VS Code Setting `editor.linkedEditing` as a replacement. This should give you same features as a workaround for now

**Comment by Zenthae** [comment]
well, this feature only works on html files, not vue ones
