### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by reslear** [windicss/windicss-intellisense#97]
- Issue Type: `Performance`
- Extension Name: `windicss-intellisense`
- Extension Version: `0.11.5`
- OS Version: `Darwin x64 20.3.0`
- VS Code version: `1.55.2`

[voorjaar.windicss-intellisense-unresponsive.cpuprofile.txt](https://github.com/windicss/windicss-intellisense/files/6352027/voorjaar.windicss-intellisense-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
<img width="603" alt="Screenshot 2021-04-21 at 18 22 26" src="https://user-images.githubusercontent.com/12596485/115579177-9283b580-a2ce-11eb-93c3-0e76b40fc1e5.png">

**Comment by alexanderniebuhr** [comment]
@reslear do you have a custom windi.config? If yes, can you please show us for repro.

**Comment by reslear** [comment]
hi @alexanderniebuhr, yes  windi.config.ts :)
```ts
import { defineConfig } from 'windicss/helpers'

export default defineConfig({
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '2rem',
      },
    },
  },
})
```

**Comment by alexanderniebuhr** [comment]
@reslear try [v0.11.6](https://github.com/windicss/windicss-intellisense/releases/tag/v0.11.6) and let me know if it is fixed, pls

**Comment by reslear** [comment]
@alexanderniebuhr  so good)) thank you) 
<img width="568" alt="Screenshot 2021-04-21 at 21 43 08" src="https://user-images.githubusercontent.com/12596485/115605008-b3f29a80-a2ea-11eb-85a9-60643f01beda.png">
